### ISSUE TITLE
JupyterLab failed to build on windows install

### ISSUE THREAD

**Issue by Ghipag** [Systems-Modeling/SysML-v2-Release#61]
Installing on windows 10 for jupyter using corresponding install.bat file, with:
- Java version 19.0.1
- conda version 23.1.0
- python 3.10

The following error is raised (shown in log file)

```
Node v18.15.0

Yarn configuration loaded.
> "C:\Program Files (x86)\nodejs\npm.CMD" pack @systems-modeling/jupyterlab-sysml@0
npm notice 
npm notice package: @systems-modeling/jupyterlab-sysml@0.33.0
npm notice === Tarball Contents === 
npm notice 441B  README.md      
npm notice 0B    build          
npm notice 7.2kB build/mode.js  
npm notice 1.2kB build/plugin.js
npm notice 0B    package        
npm notice 803B  package.json   
npm notice === Tarball Details === 
npm notice name:          @systems-modeling/jupyterlab-sysml          
npm notice version:       0.33.0                                      
npm notice filename:      systems-modeling-jupyterlab-sysml-0.33.0.tgz
npm notice package size:  3.5 kB                                      
npm notice unpacked size: 9.6 kB                                      
npm notice shasum:        566bce144e49e2216641a6c3805dd91f750c1680    
npm notice integrity:     sha512-U0pNNqBPV0jOO[...]ij1bMn+1HDAfg==    
npm notice total files:   6                                           
npm notice 
systems-modeling-jupyterlab-sysml-0.33.0.tgz
npm notice 
npm notice New minor version of npm available! 9.5.0 -> 9.6.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
npm notice Run `npm install -g npm@9.6.1` to update!
npm notice 

Node v18.15.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.47.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.47.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning " > @systems-modeling/jupyterlab-sysml@0.33.0" has unmet peer dependency "codemirror@^5.58.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 98.11s.

> node C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ C:\Users\lt17550\AppData\Local\miniconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 0.99s.

> node C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js

<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal javascript OOM in GC during deserialization
#

node:child_process:924
    throw err;
    ^

Error: Command failed: C:\Users\lt17550\AppData\Local\miniconda3\share\jupyter\lab\staging\node_modules\.bin\webpack.CMD --config webpack.prod.minimize.config.js
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.<anonymous> (C:\Users\lt17550\AppData\Local\miniconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:38:17)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  status: 2147483651,
  signal: null,
  output: [ null, null, null ],
  pid: 9924,
  stdout: null,
  stderr: null
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\commands.py", line 460, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "C:\Users\lt17550\AppData\Local\miniconda3\lib\site-packages\jupyterlab\commands.py", line 662, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```
Anyone have any thoughts how to solve this?

**Comment by seidewitz** [comment]
It looks like you may have a local configuration problem. To get more help on this, and to see if anyone else has had a similar problem, please make a post to the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release), rather than continuing with this GitHub issue.
